TITLES = {
    "serverless_image_processor": "Serverless Image Resizer",
    "ecommerce_dash": "E-Commerce Dashboard",
    "Image-Abstraction-Layer-JSON-API": "Image Search API",
    "AI_Agents": "Autonomous AI Agents",
    "llm": "LLM Experiments",
    "GenAI": "Generative AI Projects",
    "Snowflake_App_With_Streamlit": "Snowflake + Streamlit GenAI App",
    "GenAI_Sentiment": "Sentiment Analysis with GenAI",
    "AI_foundations": "AI Foundations",
    "DeepLearningSpecialization": "Deep Learning Specialization",
    "MachineLearningSpecialization": "Machine Learning Specialization",
    "Object_Detection_AI_Vision_Deployment": "YOLO Object Detection API",
    "FastAI": "FastAI Image Classifier",
    "ML_Ops": "MLOps Pipelines",
    "terraform": "Terraform Playground",
    "machine_learning": "Machine Learning with NumPy",
    "Django_ORM_CRUD": "Django CRUD with PostgreSQL",
    "project_manager": "MERN Project Manager",
    "url_shortener": "URL Shortener",
    "business_dashboard": "Data Visualization Dashboard",
    "AWS_trivia_game": "AWS Trivia Game",
    "eventDrivenApp": "Event-Driven Application",
    "AI_chatBot": "AI Chatbot",
    "AWS_Serverless": "AWS Serverless Services",
    "webscraper": "Web Scraper",
    "Legendary-Voting-App": "Voting App",
    "mybasecamper": "Basecamper",
    "Video_Image_Processor": "AI Media Resizer",
    "StackOverflowClone": "Stack Overflow Clone",
    "NextJs": "Next.js Auth",
    "React": "React Projects",
    "express-digi": "Express CRUD Demo",
    "weatherApp_JqueryMobile": "Weather App",
    "SimpleMobileApp_JqueryMobile": "Mobile App",
    "MovieApp_JQueryMobile": "Movie App",
    "MealTracker_jQueryMobile": "Meal Tracker",
    "EventManager_jQueryMobile": "Event Manager",
    "Ionic_NewsFeed": "Ionic News App",
    "Ionic_GitUsers": "Ionic GitHub Users",
    "Ionic_Firebase": "Ionic Firebase App",
    "Ionic_Auth0App": "Ionic Auth0 Auth",
    "Ionic_ToDoApp": "Ionic To-Do App",
    "FlowerShopAPP": "Flower Shop E-Commerce",
    "Legendary-Pinterest": "Pinterest Clone",
    "Legendary-Book-Store": "Online Bookstore",
    "LegendaryStocks": "Stock Market Viewer",
    "Legendary-Nightlife-Social-App": "Nightlife Social App",
    "urlShortenerService": "URL Shortener Service",
    "File-MetaData-Microservice": "File Metadata API",
    "TimeStamp-Microservice": "Timestamp API",
    "Header-Parser-Microservice": "Header Parser API",
    "React.js-playbook": "React Playground",
}
